services:
    llm-api:
        image: python:3.12-slim
        container_name: llm-api
        restart: always
        ports:
            - "8001:8001"
        expose:
            - "8001"
        volumes:
            - ./:/app
        env_file:
            - .env
        environment:
            - PYTHONUNBUFFERED=1
            - PYTHONDONTWRITEBYTECODE=1
        command: >
            bash -c "
                cd app && 
                pip install --no-cache-dir -r requirements.txt && 
                uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
            "
