services:
    llm-api:
        image: python:3.9-slim
        container_name: llm-api
        restart: always
        working_dir: /app
        ports:
            - "8001:8001"
        expose:
            - "8001"
        volumes:
            - ./:/app
        env_file:
            - .env
        environment:
            - PYTHONDONTWRITEBYTECODE=1
            - PYTHONUNBUFFERED=1
        command: >
            bash -c "pip install --no-cache-dir -r requirements.txt &&
                    fastapi run"