services:
    llm-api:
        image: python:3.12-slim
        container_name: llm-api
        restart: always
        ports:
            - "8001:8001"
        expose:
            - "8001"
        volumes:
            - ./:/app
            - chroma_db:/data/chroma_db
            - documents:/data/documents
        networks:
            - suppl-ai-shared-network
        environment:
            - PYTHONUNBUFFERED=1
            - PYTHONDONTWRITEBYTECODE=1
            - DOCUMENTS_DIR=/data/documents
            - CHROMA_DB_DIR=/data/chroma_db
        command: >
            bash -c "
                cd app && 
                pip install --no-cache-dir -r requirements.txt && 
                uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
            "
volumes:
    chroma_db:
        driver: local
    documents:
        driver: local

networks:
    suppl-ai-shared-network:
        external: true
