services:
    llm-api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8001:8001"
        volumes:
            - ./:/app
        restart: always
        env_file:
            - .env